name_en: humans
name_hi: insaan
price: '5220'
tone: premium
intent: awareness
cta_action: auto
audience: anyone
target_seconds: 89
material: flesh
usp_en:
- do work ,
- can earn money
must_say:
- but it now
